### ISSUE TITLE
colcon wants location of libpointmatcher_ros

### ISSUE THREAD

**Issue by Russ76** [norlab-ulaval/norlab_icp_mapper_ros#11]
How do I fix this error about libpointmatcher_ros? The only program I find is libpointmatcher, none have the ros extension. Where is this to be found?

colcon build --packages-select norlab_icp_mapper_ros
Starting >>> norlab_icp_mapper_ros
--- stderr: norlab_icp_mapper_ros                         
CMake Error at CMakeLists.txt:14 (find_package):
  By not providing "Findlibpointmatcher_ros.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "libpointmatcher_ros", but CMake did not find one.

 Could not find a package configuration file provided by
  "libpointmatcher_ros" with any of the following names:

    libpointmatcher_rosConfig.cmake
    libpointmatcher_ros-config.cmake

  Add the installation prefix of "libpointmatcher_ros" to CMAKE_PREFIX_PATH
  or set "libpointmatcher_ros_DIR" to a directory containing one of the above
  files.  If "libpointmatcher_ros" provides a separate development package or
  SDK, be sure it has been installed.

---
Failed   <<< norlab_icp_mapper_ros [3.06s, exited with code 1]

Summary: 0 packages finished [4.06s]
  1 package failed: norlab_icp_mapper_ros
  1 package had stderr output: norlab_icp_mapper_ros

**Comment by simonpierredeschenes** [comment]
Hi @Russ76, thank you for using norlab_icp_mapper_ros! libpointmatcher_ros is a ROS wrapper for libpointmatcher that we created. It is available here: https://github.com/norlab-ulaval/libpointmatcher_ros. Don't hesitate if you have other questions.

**Comment by Russ76** [comment]
OK, I made a new workspace and added all three repos that look like they work together. But compilation with "colcon build" comes up with this error:

Finished <<< libpointmatcher_ros [9.91s]
Starting >>> norlab_icp_mapper_ros
--- stderr: norlab_icp_mapper_ros                          
CMake Error at CMakeLists.txt:17 (find_package):
  By not providing "Findnorlab_icp_mapper.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "norlab_icp_mapper", but CMake did not find one.

  Could not find a package configuration file provided by "norlab_icp_mapper"
  with any of the following names:

    norlab_icp_mapperConfig.cmake
    norlab_icp_mapper-config.cmake

  Add the installation prefix of "norlab_icp_mapper" to CMAKE_PREFIX_PATH or
  set "norlab_icp_mapper_DIR" to a directory containing one of the above
  files.  If "norlab_icp_mapper" provides a separate development package or
  SDK, be sure it has been installed.

---
Failed   <<< norlab_icp_mapper_ros [3.13s, exited with code 1]

Summary: 2 packages finished [14.1s]
  1 package failed: norlab_icp_mapper_ros
  3 packages had stderr output: libpointmatcher_ros norlab_icp_mapper norlab_icp_mapper_ros

I'm using Ubuntu 22.04 and Ros2 Humble. It's a Ryzen 7 laptop with 16Gig RAM. Thanks! Russ

**Comment by simonpierredeschenes** [comment]
norlab_icp_mapper is the SLAM library that is wrapped by norlab_icp_mapper_ros. It is a standard c++ library, which must be installed on your system outside your ROS workspace. It is available here: https://github.com/norlab-ulaval/norlab_icp_mapper. However, in order to install norlab_icp_mapper, you must first install libnabo (https://github.com/norlab-ulaval/libnabo) and then libpointmatcher (https://github.com/norlab-ulaval/libpointmatcher).

**Comment by Russ76** [comment]
OK, that makes sense. I'll try that next. Thanks
