### ISSUE TITLE
Instabilities in large scale localisation

### ISSUE THREAD

**Issue by JMtSG** [norlab-ulaval/norlab_icp_mapper_ros#2]
We've successfully used norlab_icp_mapper_ros to localise our wheeled robot in part of an industrial plant (~200 x 80 meters).  We're matching VLP-16 scans to a point cloud map acquired a priori with a high-quality Leica scanner. 

The mapper node has is_mapping​​ disabled and is running in 3D, with force4DOF​​ set (we have good pitch/roll estimates). 

This setup runs very well in a limited area of the plant (30 x 30 meters); however, we've started experiencing localisation failures and ConvergenceErrors when the robot travels over 50-100m away from the map origin. 

We read your "Large-scale 3D Mapping of Subarctic Forests" paper in detail. Did you experience any instabilities in this large-scale mapping work?  Did you have to use submapping or change anything in libpointmatcher​? (e.g. offsetting the map to ensure ICP was performed close to the origin?)  

Thanks

**Comment by simonpierredeschenes** [comment]
Hi @JMtSG, what version of the norlab_icp_mapper do you use (commit number)? We recently added a feature that allows map tile offloading on disk. This might help with large-scale localization stability issues. As for libpointmatcher, we did not have to change anything, it already takes care of offsetting the point clouds close to the origin if I remember correctly.

**Comment by JMtSG** [comment]
Thanks for the suggestion Simon. We tested your latest version with the map tile offloading feature, and no longer experienced the localisation failures and ConvergenceErrors we previously had.
Was this also the version you used in your "Large-scale 3D Mapping of Subarctic Forests" paper? Or did you have any other publication outlining the version update?

**Comment by simonpierredeschenes** [comment]
@JMtSG I'm glad you were able to make it work! This feature was not used in "Large-scale 3D Mapping of Subarctic Forests" and was not mentioned in any work yet. If I remember correctly, the maps made in this paper were made in post-processing, so I guess they were slowing down the playback rate to do their mapping. This allowed them to localize more often, thereby avoiding the ConvergenceError you experienced.
