### ISSUE TITLE
TF problem with custom dataset

### ISSUE THREAD

**Issue by Cristian-wp** [norlab-ulaval/norlab_icp_mapper_ros#6]
Hello.
I have manage to run the package, but when I perform the launch of the node and play my rosbag I get this error:

`Could` not find a connection between 'odom' and 'os_sensor' because they are not part of the same tree.Tf has two or more unconnected trees.`

- os_sensor is my ouster lidar reference frame, I have already define the trasformation in the launch file:

` <node pkg="tf" type="static_transform_publisher" name="baselink2ossensor" args="0 0 0.35 0 0 0 base_link os_sensor 100" />`

- And also try to use robot_state_publisher creating my robot.urdf (base_link --> os_sensor), but nothing change

- I have launch `rosrun tf view_frames` and odom and base_link are not connected. 
map-->odom       
base_link-->os_sensor-->other_sensor

- I have check inside mapper_node.cpp if the frame was get by the topic and is readed.
```
void gotInput(const PM::DataPoints& input, const std::string& sensorFrame, const ros::Time& timeStamp)
{
	std::cout<<"***********************************************************"<<std::endl;
	std::cout<<"gotInput - sensorFrame= "<<sensorFrame<<std::endl;
	std::cout<<"***********************************************************"<<std::endl;

	try
	{
		PM::TransformationParameters sensorToOdom = findTransform(sensorFrame, params->odomFrame, timeStamp, input.getHomogeneousDim());
		PM::TransformationParameters sensorToMapBeforeUpdate = odomToMap * sensorToOdom;

```
terminal output:
```
***********************************************************
[ WARN] [1664972719.869161948]: Could not find a connection between 'odom' and 'os_sensor' because they are not part of the same tree.Tf has two or more unconnected trees.
***********************************************************
sensorFrame= os_sensor
***********************************************************
[ WARN] [1664972719.970950482]: Could not find a connection between 'odom' and 'os_sensor' because they are not part of the same tree.Tf has two or more unconnected trees.
***********************************************************
sensorFrame= os_sensor
***********************************************************
[ WARN] [1664972720.076061064]: Could not find a connection between 'odom' and 'os_sensor' because they are not part of the same tree.Tf has two or more unconnected trees.
***********************************************************
sensorFrame= os_sensor
***********************************************************
```
How I can connect the odom and base_link frame?

**Comment by simonpierredeschenes** [comment]
Ok, so in the first problem you mentioned,  where the mapper outputs that there is no connection between base_link and os_sensor, is it printed continuously or just a few times when you start the mapper? And for your other problem (the connection between base_link and odom), you need to have an odometry node that will publish this tf. This will be used as a prior for localization. Usually,  these odometry nodes are based on wheel encoders and an IMU. If your platform doesn't have wheels,  you can use [our odometry node](https://github.com/norlab-ulaval/imu_odom) which uses the IMU and previous pose computed by the mapper. This odometry node is still in development though,  so it is not perfect.

**Comment by Cristian-wp** [comment]
1) Is printed continuosly, in my dataset the robot stay still for 5s then start moving. Even after 10m the message is still printed.

2) "you need to have an odometry node that will publish this tf", can you explain better this part? If I understand correctly, I need anther node that publish a nav_msgs/odometry message with thr frame named "odom" (default). In this way the icp take automatically as input the topic?
Can I use a visual-inertial slam ad odometry input or is not compatible?

Thanks for your fast reply, there is a tutorial/paper or other documents with the "instructions"?

**Comment by simonpierredeschenes** [comment]
1. Ok, then this means that the mapper is not able to lookup the TF between base_link and os_sensor for some reason. Maybe if you try to launch the mapper before your static_transform_publisher, this could solve your issue.
2. TFs do not come from odometry messages. TFs are a special kind of message that are handled differently. You need a node that will broadcast the TF between the odom and base_link frames. Here is a tutorial that explains how to create a TF broadcaster: [Writing a tf2 broadcaster (C++)](http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20broadcaster%20%28C%2B%2B%29). In the mapper, we use a [TF listener](http://wiki.ros.org/tf2/Tutorials/Writing%20a%20tf2%20listener%20%28C%2B%2B%29) to access the TF between odom and base_link. I think you could use a visual-inertial SLAM as odometry, but you will need to make sure that the odom_frame parameter of the mapper is set to the proper value.

Unfortunately, there is no documentation yet on how to use our mapper, but this is definitely something we want to add in the future!

**Comment by Cristian-wp** [comment]
Ok, I have manage to make it work, but with the imu odom id map is not generated well. I think because ICP is not well tuned to work in a concrete tunnel with completely flat walls. Now I try to substitute it with a visual slam as primary source of odom and I let you know!
Thanks a lot!
If you can I need some help to tune the ICP for my cases. 
I need to open a new issue or we can use this one?

**Comment by simonpierredeschenes** [comment]
I don't think that this repository is the right place to discuss ICP parameter tuning. We use the libpointmatcher library to register our point clouds. There are some good resources on their [github repository](https://github.com/ethz-asl/libpointmatcher/blob/master/doc/index.md). I hope you will be able to make it work for your application.

**Comment by Cristian-wp** [comment]
Hi @simonpierredeschenes sorry to reopen this question but I really need some clarification.
I have trying to understand the strategy you hade use for the ICP but I can not manage to progress.

As you suggest I had a look on libpointmatcher in order to tune the parameters listed in NodeParameters.cpp, these three in particular:
```
	nodeHandle.param<std::string>("icp_config", icpConfig, "");
	nodeHandle.param<std::string>("input_filters_config", inputFiltersConfig, "");
	nodeHandle.param<std::string>("map_post_filters_config", mapPostFiltersConfig, "");
```
I think that are related to this page [https://libpointmatcher.readthedocs.io/en/latest/DataFilters/](DataFilters) in order to create a yaml with some filter chain.
But there are other like:
```
	nodeHandle.param<float>("min_dist_new_point", minDistNewPoint, 0.03);
	nodeHandle.param<float>("sensor_max_range", sensorMaxRange, 80);
	nodeHandle.param<float>("prior_dynamic", priorDynamic, 0.6);
	nodeHandle.param<float>("threshold_dynamic", thresholdDynamic, 0.9);
	nodeHandle.param<float>("beam_half_angle", beamHalfAngle, 0.01);
```

that are like some of the filter that can be put in the yaml config file.

So the question is, there are already some filter chan implemented in the code (if yes where)? 
Do you have some example of these yaml files "use in a real test"? In libpointmatcher there are some, but are generic and more important I do not know if in the actual code there is a filter chain already.

Can you please tell me how to proceed, or maybe link me some documentation to be indipendent?
Thank you in advance.

**Comment by simonpierredeschenes** [comment]
Hi @Cristian-wp, the icp_config parameter is the path to a file that contains a libpointmatcher config file, as described in https://libpointmatcher.readthedocs.io/en/latest/Configuration/. As for the input_filters_config and map_post_filters_config parameters, they contain paths to config files of DataPointsFilter chains that are applied to the input point cloud before registration and to the new map after registration respectively. Here is an example of how to configure a DataPointsFilter chain: https://libpointmatcher.readthedocs.io/en/latest/ApplyingDataFilters/. The other parameters you mentioned should be described in the Readme file of this repository. Here is a tutorial explaining the basics of our mapper: https://github.com/norlab-ulaval/Norlab_wiki/wiki/Tutorials:-3D-Mapping. Here is a repository with the launch files we use to do real time mapping on our robot: https://github.com/norlab-ulaval/warthog_mapping

**Comment by Cristian-wp** [comment]
Thanks a lot!!!!!!
