### ISSUE TITLE
How to save the map?

### ISSUE THREAD

**Issue by Cristian-wp** [norlab-ulaval/norlab_icp_mapper_ros#8]
I am trying to save the map using the SaveMap.srv service but I can not manage to get the vtk file.
I have already define the path+name in my params in the launch file, but even if I stop the node nothing appears.
What is the correct procedure?

**Comment by simonpierredeschenes** [comment]
Hi @Cristian-wp ! What branch of the mapper are you using?

**Comment by Cristian-wp** [comment]
Hi, I am using the melodic one

**Comment by simonpierredeschenes** [comment]
The `final_map_file_name` parameter is used when the mapper is in offline mode. This parameter will tell the mapper where to store the final map once the mapper is done processing all the data it has to process. When using the mapper in online mode (the default mode), you have to use the /save_map service. If you enter the following command in a terminal and press TAB a couple of times when the mapper is running, it should autocomplete the command and you will be able to specify the file in which you want to save the map:
```bash
rosservice call /save_map
```

**Comment by Cristian-wp** [comment]
I had try, but when I launch :
rosservice call /save_map map_name.vtk 
The service give me an error about map_name.vtk, because map_name.vtk is not std_msgs/String type.
I have even try without the file name, but it give me an error, because is needed.

**Comment by simonpierredeschenes** [comment]
It seems like the syntax is not good, make sure to use the autocomplete to make sure that the service call is properly structured

**Comment by Cristian-wp** [comment]
Ok, I will try and let you know tomorrow.
Stupid question, I have to launch the service at the end of the mapping process right?

**Comment by simonpierredeschenes** [comment]
Perfect! As for the timing of the service call, the save_map service will save the current state of the map, so if you want to save the complete map, you have to call it at the end of the mapping process.

**Comment by Cristian-wp** [comment]
Hi @simonpierredeschenes , I have manage to save the map!
Thank you for your help!
But if I can give you a suggestion, I think it will be better put an explanation about the procedure in the description of the page, because in order to save a map you need to put the following command:
`rosservice call /save_map "map_file_name:
  data: '/home/.../map/map_name.vtk'"`
This comes out as you say from autocomplete, but if you try do it only whatching SaveMap.srv you encounter my previous problems:
```
1.

$ rosservice call /save_map 
Usage: rosservice call /service [args...]

rosservice: error: Please specify service arguments`
```

2)
```
rosservice call /save_map name.vtk
ERROR: Incompatible arguments to call service:
No key named [name.vtk]
Provided arguments are:
 * name.vtk (type str)

Service arguments are: [map_file_name.data]
```

**Comment by simonpierredeschenes** [comment]
I am glad that it worked! This is definitely something that we should clarify in the future. Thanks for the feedback!
